public enum AuditLogEvent
{
    LoginSuccess,
    LoginFailed,
    AccountLocked,
    TokenRefreshed,
    Logout,
    LogoutAllDevices,
    PasswordResetRequested,
    PasswordResetCompleted,
    TwoFactorEnabled,
    TwoFactorSetup,
    TwoFactorSuccess,
    TwoFactorFailed,
    EmailConfirmed,
    UserRegistered,
    TwoFactorDisabled,
    TwoFactorRecoveryRequested,
    TwoFactorRecoveryCompleted
}
